spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: 1s
